close modal bug with escape and button
1Hive/quests pull request #100
Opened 2021-12-26 22:47 UTC by alexchan0394

2021-12-26 23:51 UTC, Corantin requested changes

2021-12-26 23:51 UTC, Corantin commented on packages/react-app/src/components/modals/modal-base.tsx
> +      (e.target.tagName.toUpperCase() === 'BODY' || e.target.type?.toLowerCase() === 'button')
Rajoute un TODO : Not clean

2021-12-26 23:51 UTC, Corantin commented on packages/react-app/src/components/modals/modal-base.tsx
> +      onClose();
Si je me souviens bien, ça appelait la fonction 4 fois donc tu pourrais utiliser un debouncer pour fix sa
Ya un exemple dans quest-list.tsx:55:
![image](https://user-images.githubusercontent.com/13890618/147422728-3247c3b1-7e93-4831-8225-d83c6828bbf1.png)
![image](https://user-images.githubusercontent.com/13890618/147422746-4fbbd3f3-46ef-41de-9513-6e98fb3a2a2c.png)

2021-12-27 00:42 UTC, Corantin requested changes

2021-12-27 00:42 UTC, Corantin commented on packages/react-app/src/components/shared/utils/spacer-util.tsx
> +    else if (gu8) classes += ' p-8';
je t'ai induit en erreur sry le else if (gu8) faut le mettre last line paske vu ye tjrs true sa va shadow le reste meme si on met 16 a true sa sra 8

2021-12-27 00:42 UTC, Corantin commented on packages/react-app/src/components/shared/quest.tsx
> +          <Outset>
En fait le vrai truc c'est gu16={questMode===QUEST_MODE.Create||questMode===QUEST_MODE.Edit}
Paske je toruve sa trop tight sinon en mode read 
![image](https://user-images.githubusercontent.com/13890618/147423566-cffe1944-6c13-429f-b8f0-3b695ea10b8d.png)

2021-12-27 07:56 UTC, alexchan0394 commented on packages/react-app/src/components/modals/modal-base.tsx
> +      (e.target.tagName.toUpperCase() === 'BODY' || e.target.type?.toLowerCase() === 'button')
done

2021-12-27 07:57 UTC, alexchan0394 commented on packages/react-app/src/components/modals/modal-base.tsx
> +      onClose();
Même avec l'ajout d'un Debounce(callback, 500), l'event se call 5 fois encore

2021-12-27 07:57 UTC, alexchan0394 commented on packages/react-app/src/components/shared/utils/spacer-util.tsx
> +    else if (gu8) classes += ' p-8';
Done

2021-12-27 07:59 UTC, alexchan0394 commented on packages/react-app/src/components/shared/quest.tsx
> +          <Outset>
tu veux que je crée un QUEST_MODE.Edit à la place de QUEST_MODE.Update pour cette classe? 
![image](https://user-images.githubusercontent.com/47338497/147449346-d5a17c9e-ad0b-4267-9b1b-7063d6305a16.png)

2021-12-28 00:05 UTC, Corantin approved these changes

2021-12-28 00:08 UTC, Corantin approved these changes

2021-12-28 00:19 UTC, merged