Stepper
1Hive/quests pull request #235
Opened 2022-04-15 23:04 UTC by kafann

close #178

2022-04-16 13:24 UTC, Corantin commented
Finalement je pensse sa serait plus lisible si c'etait la meme taille

2022-04-17 13:54 UTC, Corantin requested changes
Tu pourra merge apres sa, jai fait pas mal de truc dans ta PR mb haha jai add sa :
- Wallet balance dans quest
- Disable Create quest button when form invalid
- Le reste jpensse jte lai dit

2022-04-17 13:54 UTC, Corantin commented on packages/react-app/src/components/modals/quest-modal.tsx
> +      // buttons={[
Remove comments

2022-04-17 13:54 UTC, Corantin commented on packages/react-app/src/components/modals/schedule-claim-modal.tsx
> +        // validateOnBlur
Remove comments

2022-04-20 13:21 UTC, Corantin approved these changes

2022-04-20 14:40 UTC, Corantin approved these changes
To Validate : 
- [x] Stepper in create Quest modal
- [x] Stepper in Schedule Claim modal
- [x] Wallet balance is now in create Quest modal and should show a loading feedback
- [ ] Claim list in Quest detail should show loading as well as no content feedback
- [ ] Amount field input should show loading feedback (in placeholder)

2022-04-20 16:44 UTC, alexchan0394 commented
**Wallet balance is now in create Quest modal and should show a loading feedback** 

When creating a quest, unselecting a token will show loading of the wallet balance when it should be "No Token Selected" 

- Create quest
- Select a token
- Deselect token
- Click BACK 
- Click NEXT
- You should see no token selected with a loading wallet balance

![image](https://user-images.githubusercontent.com/47338497/164281312-9bdcffe3-4ba2-43fc-93ac-f5639a9ef200.png)

2022-04-20 16:53 UTC, Corantin commented
> **Wallet balance is now in create Quest modal and should show a loading feedback**
> 
> When creating a quest, unselecting a token will show loading of the wallet balance when it should be "No Token Selected"

Solved by [fce349a](https://github.com/1Hive/quests/pull/235/commits/fce349ad9f52535eae019ead11a9e93727cf319b)

2022-04-20 17:20 UTC, alexchan0394 commented
> To Validate :
> 
> * [x]  Stepper in create Quest modal
> * [x]  Stepper in Schedule Claim modal
> * [x]  Wallet balance is now in create Quest modal and should show a loading feedback
> * [x]  Claim list in Quest detail should show loading as well as no content feedback
> * [x]  Amount field input should show loading feedback (in placeholder)

I checked everything and it should be good to go

2022-04-20 17:27 UTC, merged